// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rokafela/udemy-banking-auth/domain (interfaces: LoginRepository)

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/rokafela/udemy-banking-auth/domain"
	errs "github.com/rokafela/udemy-banking-lib/errs"
)

// MockLoginRepository is a mock of LoginRepository interface.
type MockLoginRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginRepositoryMockRecorder
}

// MockLoginRepositoryMockRecorder is the mock recorder for MockLoginRepository.
type MockLoginRepositoryMockRecorder struct {
	mock *MockLoginRepository
}

// NewMockLoginRepository creates a new mock instance.
func NewMockLoginRepository(ctrl *gomock.Controller) *MockLoginRepository {
	mock := &MockLoginRepository{ctrl: ctrl}
	mock.recorder = &MockLoginRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginRepository) EXPECT() *MockLoginRepositoryMockRecorder {
	return m.recorder
}

// FindUserByCredential mocks base method.
func (m *MockLoginRepository) FindUserByCredential(arg0, arg1 *string) (*domain.Login, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByCredential", arg0, arg1)
	ret0, _ := ret[0].(*domain.Login)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// FindUserByCredential indicates an expected call of FindUserByCredential.
func (mr *MockLoginRepositoryMockRecorder) FindUserByCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByCredential", reflect.TypeOf((*MockLoginRepository)(nil).FindUserByCredential), arg0, arg1)
}

// SaveToken mocks base method.
func (m *MockLoginRepository) SaveToken(arg0 *string) *errs.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", arg0)
	ret0, _ := ret[0].(*errs.AppError)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockLoginRepositoryMockRecorder) SaveToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockLoginRepository)(nil).SaveToken), arg0)
}
